### ISSUE TITLE
заменить картинку crab1.png

### ISSUE THREAD

**Issue by tconsts** [tconsts/pefladdons#10]
в данный момент в некоторых местах, а точнее даже всегда, так как в common скрипте, пытается загрузится ссылка на картинку из старого, удаленного репозитория
http://pefladdons.googlecode.com/svn/trunk/img/crab1.png
надо ее убрать, в идеале заменить на локальную картинку которая идет с пакетом в папке img

**Comment by avladykin** [comment]
Исправлено

**Comment by tconsts** [comment]
поставил ФИКСЕД, и реопнул до момента релиза
как билд в магазин выложу - закрою
