### ISSUE TITLE
отключить Номинал+

### ISSUE THREAD

**Issue by tconsts** [tconsts/pefladdons#15]
ну или по крайней мере если не вырезать из кода, то сделать выключалку и поставить в дефоулт как выкл
ну чтоб если люди начнут просить вернуть, можно было бы быстро вернуть - но вообще не должны быть просить - он же че попало щас показывает

**Comment by avladykin** [comment]
Вы че, я же на него только и ориентируюсь когда покупаю-продаю игроков!

**Comment by tconsts** [comment]
тогда на трюфика надо тыкателя натравить чтоб пушил :D
