### ISSUE TITLE
Summary в истории встреч

### ISSUE THREAD

**Issue by tconsts** [tconsts/pefladdons#21]
[quote][b]serge78 :[/b]
Я бы добавил в историю встреч  summary какое то, ибо за 14-15 сезонов встреч накопилось больше 50 и посчитать кто круче очень тяжело :)
[/quote]

**Comment by kekemeke** [comment]
@tconsts оно же вроде реализовано уже, не?
![image](https://user-images.githubusercontent.com/15379402/90315218-211b8800-df33-11ea-8a11-aaab0ca58a04.png)

**Comment by tconsts** [comment]
ога, кто-то сделал и не закрыл, не буду показывать пальцем но это был слоненок :)

**Comment by eugenkondratiev** [comment]
потому-то не умел я в совместную разработку. хз что еще закрывать надо что-то:).

а чего конст решил добраться вдруг до репозитория и привести все в порядок?  выход на новый магазин?
