### ISSUE TITLE
Решить проблему с кодировками

### ISSUE THREAD

**Issue by vesellov** [tconsts/pefladdons#37]
Друзья, что-то нужно решать с кодировками...

Я так понимаю что автор использует Windows и весь проект поэтому в `Windows-1251` ...

Пробовал я добавить `.gitattributes` что бы у меня на Debian все работало нормально. Но потом кто-то решил это удалить - вероятно на его машине кодировки из-за этого съехали.

Не делают жизнь проще еще и окончания строк - в Linux это просто `\n` а под виндой это `\r\n`...  Обычно я такое исправляю с помощью `dos2unix` - но тогда у тех кто использует Windows появятся проблемы при работе с файлами проекта вероятно...

У меня нет практического опыта решения таких проблем - всю жизнь работал с git только под Linux и если нужно было вставить что-то не на английском - это никогда не было проблемой.

Есть идеи, предложения?

**Comment by tconsts** [comment]
cp-1251 это потому что сам pefl имеет эту кодировку на сайте - а часть функционала четко вставляется по русски как есть
и как бы вести все в utf-8, регулярно перекодируя тот еще гиморой, его достаточно при ипользовании аякса

а окончания строк вроде пофигу

**Comment by tconsts** [comment]
а сейчас в каком состоянии в плане кодировок проект-то?
у кого что не работает?
собрать-то его и выложить в магазин можно?

**Comment by vesellov** [comment]
окей.... вроде разобрались.
