### ISSUE TITLE
На старой версии ростера игрока крабвип не работает

### ISSUE THREAD

**Issue by ba11ak** [tconsts/pefladdons#7]
Баг от и для sanyok

**Comment by tconsts** [comment]
надо в истории коммитов посмотреть тот момент когда я переключал на новый ростер и наверное как-то сделать чтоб работало сразу на двух

**Comment by avladykin** [comment]
peflplayer.js Revision 1222 16 августа 2014 года 22:08:46

**Comment by avladykin** [comment]
Исправлено

**Comment by tconsts** [comment]
поставил ФИКСЕД, и реопнул до момента релиза
как билд в магазин выложу - закрою
