### ISSUE TITLE
Добавить информативных картинок к отчету на матч

### ISSUE THREAD

**Issue by ba11ak** [tconsts/pefladdons#8]
События:

Замена - изменить иконку
Офсайд
Пенальти - незабитый/забитый
Угловой
Штрафной
Автогол - другая иконка
Завершение первого тайма
Дополнительное время

**Comment by ba11ak** [comment]
https://s-media-cache-ak0.pinimg.com/736x/d9/f7/55/d9f75508f0f3afd5b9ddb4d695394f19.jpg
https://d13yacurqjgara.cloudfront.net/users/146773/screenshots/1215190/game_icon.png

**Comment by ba11ak** [comment]
+ Гол
+ Замена - изменить иконку
+ Офсайд
Пенальти - незабитый/забитый
+ Угловой
+ Штрафной
Автогол - другая иконка
Завершение первого тайма
Дополнительное время

**Comment by ba11ak** [comment]
Еще хорошо бы поставить иконки справа/слева в зависимости от того в какую сторону событие (более информативно).

**Comment by ba11ak** [comment]
Еще хорошо бы контры сразу указывать.

**Comment by ba11ak** [comment]
Добавил : пенальти, дополнительное время, карточки, травмы.

Есть еще некоторые доработки которые можно сделать, но думаю для этого можно уже отдельный тикет создать, чтобы не плестись с одним и тем же.

**Comment by tconsts** [comment]
таки делается в рамках проекта Краба

**Comment by ba11ak** [comment]
Угу. Для начала

**Comment by tconsts** [comment]
вошло в 2.0.6
