### ISSUE TITLE
Переделать Состав+ на новый состав на матч

### ISSUE THREAD

**Issue by tconsts** [tconsts/pefladdons#9]
проблема в том что текущие данные скрипт берет из старого источника (определенный файл вида .php), там данные берутся из пхп и парсятся загоняя их в js
необходимо переделать на новый источник (данные вида json), урл откуда брать можно взять из localStorage, ключ вида sostavurl1432 где 1432 id команды
урл туда записывается когда открывается страница выставления состава
ну и плюс надо не только их получить, но и преобразоваться в нужный вид естественно

**Comment by ba11ak** [comment]
Зашел. Разобраться сложно, но понятно с чего начинать )

**Comment by ba11ak** [comment]
Сейчас берет из http://pefl.ru/fieldnew3.php
надо чтобы брал из
http://pefl.ru/jsonsostav.php?j=795&u=9724&r=281625&m=get&z=7e3e968223e55ead0d1544cdf019f8f2
пока что неясно откуда брать эти параметры
Как вариант - скачать страничку состава на матч и там получить и json url.

**Comment by tconsts** [comment]
яж написал что сейчас этот урл откладывается в localStorage - там урл и взять надо
ну и формат другой - я частично начал это делать, но не закончил

**Comment by ba11ak** [comment]
Сделал quickfix - теперь отображаются правильные изначальные позиции.
Для того чтобы полностью переделать надо по-больше времени. Хорошо что хоть понял где надо было фиксить.

**Comment by ba11ak** [comment]
Конечно если ссылка на старый состав будет удалена то ничего уже не загрузится, но пока что не вижу смысла девить лишь для того чтобы был чистый код, есть фишки по-важнее )

**Comment by tconsts** [comment]
вынужден сделать реопен, чет сразу не сообразил...
еще надо же состав взять - те кто в основе и те кто на замене, сейчас они помечаются не правильно так как берутся со старого

**Comment by tconsts** [comment]
хм, и еще...
у нас по коду идет несколько вызовов GetData('positions')
к вызову добавлен obj тока при одном вывозе, в остальных без него(будет undefined)
а в самой функции GetData этот obj пробрасывается в  FillHeaders(obj)
а в FillHeaders obj не проверяется и сразу идет for (j in obj.sostav1)

**Comment by ba11ak** [comment]
Ага, понял. Я проверил только основной сценарий, не знаю какие там еще бывают )

**Comment by tconsts** [comment]
опубликовал в магазинах, вошло в версию 2.0.5
